# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishCucumberReport@1
  inputs:
    jsonDir: 'target/cucumber-report'
    outputPath: 'target/cucumber-report'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true


- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()


# - task: SendEmail@1
#   inputs:
#     to: 'developers@example.com'
#     subject: 'Build status: $(System.DefinitionName) $(Build.BuildNumber)'
#     body: |
#       <html>
#       <body>
#       <h1>Build Status</h1>
#       <p>The build <strong>$(Build.BuildNumber)</strong> of <strong>$(System.DefinitionName)</strong> is <strong>$(Build.Status)</strong></p>
#       <p>You can check the pipeline details <a href="$(System.TeamFoundationCollectionUri)/$(System.TeamProject)/_build?definitionId=$(Build.DefinitionId)&_a=summary">here</a></p>
#       </body>
#       </html>
#     isHtml: true



# - task: SendEmail@1
#   inputs:
#     To: 'rkandregula3@gmail.com'
#     From: 'reshma.kandregula@capgemini.com'
#     Subject: 'Dashboard and Status'
#     Body: |
#       Am sending the status of the cicd pipeline.
#       PFA
#     BodyAsHtml: true
#     AddAttachment: true
#     Attachment: 'C:\Users\RKANDREG\OneDrive - Capgemini\Documents\OneDrive - Capgemini\Microsoft Teams Chat Files'


# - task: SendEmail@1
#   inputs:
#     To: 'deepika.narayanappa@capgemini.com'
#     From: 'reshma.kandregula@capgemini.com'
#     Subject: 'Dashboard'
#     Body: 'Chumma da'
#     BodyAsHtml: true
#     # AddAttachment: true
#     # Attachment: 'AllureReport.docx'
#     SmtpServer: 'smtpout.secureserver.net'
#     SmtpUsername: 'reshma.kandregula@capgemini.com'
#     SmtpPassword: '71nku34l81N'


# - task: SendEmail@1
#   inputs:
#     To: 'deepika.narayanappa@capgemini.com'
#     From: 'reshma.kandregula@capgemini.com'
#     Subject: 'dashboard and status'
#     Body: 'Created new'
#     BodyAsHtml: true
#     AddAttachment: true
#     Attachment: 'C:\Users\RKANDREG\OneDrive - Capgemini\Documents\OneDrive - Capgemini\Documents\allure-report\AllureReport.docx'
#     SmtpServer: 'smtpout.secureserver.net'
#     SmtpUsername: 'reshma.kandregula@capgemini.com'
#     SmtpPassword: '71nku34l81N'

# - task: SendEmail@1
#   inputs:
#     To: 'deepika.narayanappa@capgemini.com'
#     From: 'reshma.kandregula@capgemini.com'
#     Subject: 'dashboard and status'
#     Body: 'Created new'
#     BodyAsHtml: true
#     # AddAttachment: true
#     # Attachment: 'Sys'
#     SmtpServer: 'smtpout.secureserver.net'
#     SmtpUsername: 'reshma.kandregula@capgemini.com'
#     SmtpPassword: '71nku34l81N'
 
  
  

# steps:
- task: agent-screenshot@1
  condition: and( failed(), passed())